name: 'Sync Upstream Branch'

on:
  schedule:
    - cron: '0 */4 * * *' # scheduled every 4 hours
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo
    steps:
    - name: Checkout target repo
      uses: actions/checkout@v3
      with:
        ref:  MAKE-PRS-HERE
        persist-credentials: false
    - name: Sync upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
      with:
        target_sync_branch: MAKE-PRS-HERE
        target_repo_token: ${{ secrets.GH_PAT }}
        upstream_sync_branch: MAKE-PRS-HERE
        upstream_sync_repo: FrogAi/FrogPilot

    - name: New commits found
      if: steps.sync.outputs.has_new_commits == 'true'
      run: echo "New commits were found to sync."

    - name: No new commits
      if: steps.sync.outputs.has_new_commits == 'false'
      run: echo "There were no new commits."

    - name: Show value of 'has_new_commits'
      run: echo ${{ steps.sync.outputs.has_new_commits }}
